language: c
sudo: false
dist: xenial

os:
  - linux

compiler:
  - gcc
  - clang

arch:
  - arm64
  - amd64
  - s390x
  - ppc64le

matrix:
  include:
    - os: osx
      arch: amd64
      compiler: clang

script: make
