language: c
sudo: false
dist: xenial

env:
  - CFLAGS="-Wall -W -O"

os:
  - linux

compiler:
  - gcc
  - clang

arch:
  - arm64
  - amd64

matrix:
  include:
    - arch: s390x
      compiler: clang
    - arch: ppc64le
      compiler: clang      
    - os: osx
      arch: amd64
      compiler: clang

script: make
