name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: make
        run: make

  macOS-build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@master
      - name: make
        run: make
